
# auto-generated by configure
PREFIX = /usr/local
VERSION = 2.7.3
CC = gcc
CFLAGS = -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas
LDFLAGS =  -lm

